feat(terser): Update WorkerPool to reuse Workers
rollup/plugins pull request #1409
Opened 2023-01-19 23:00 UTC by dasa

## Rollup Plugin Name: `terser`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: https://github.com/rollup/plugins/pull/1341#pullrequestreview-1176576290

### Description

The existing WorkerPool creates a new Worker instance for every chunk. This PR reuses them instead. There is still a max number of workers, and the pool size still increases based on demand up to this max.

In my testing, on a 10 CPU machine, this reduced the build time from about 4.5 minutes to 2.5 minutes. This is for a large project with about 8,000 chunks.

I refactored the WorkerPool based on [this](https://nodejs.org/dist/latest-v18.x/docs/api/async_context.html#using-asyncresource-for-a-worker-thread-pool) Node doc example. I changed it to not create all the workers immediately though since this isn't needed in simple cases.

The changes to `module.ts` are based on the logic in https://github.com/TrySound/rollup-plugin-terser/blob/master/rollup-plugin-terser.js This is needed since the Workers now need to be explicitly terminated.

2023-01-20 16:58 UTC, dasa commented
@tada5hi can you review this please?

2023-01-20 23:29 UTC, shellscape reviewed
`tests included` was checked, and while technically there are tests, they were only modified to check for a new error value. I'd like to see some more robust testing in place to prevent regression: something like providing some basic reporting from the plugin that we could analyze - namely the number of workers used, so that worker re-use could be verified. Note that I'm not speaking about log output specifically, but if that's the only option then that would work.

2023-01-20 23:46 UTC, dasa commented
> something like providing some basic reporting from the plugin that we could analyze

Is there another plugin that has something like this so I can see how the mechanics of that could work? e.g., is it another export from the `index` module? Currently the worker pool instance is in the scope of the default function exported from the `module` module.

2023-01-20 23:48 UTC, shellscape commented
there isn't to my knowledge, which is part of the reason I left it open-ended. I wouldn't even care if it was really dirty, just seeking to protect your changes against regression in the future. Give it a poke, and if at the end you don't have anything that's usable for determining that in a test, we'll make a note and move on.

2023-01-21 17:43 UTC, tada5hi commented
> @tada5hi can you review this please?
left you some notes

2023-01-21 18:06 UTC, dasa commented
@shellscape I've updated the tests.

@tada5hi sorry, I'm not seeing the notes.

2023-01-21 18:22 UTC, tada5hi requested changes

2023-01-21 18:23 UTC, tada5hi commented
> @tada5hi can you review this please?



> @shellscape I've updated the tests.
> 
> @tada5hi sorry, I'm not seeing the notes.

sorry i forgot to submit the review :see_no_evil:

2023-01-22 17:28 UTC, dasa commented on packages/terser/src/worker-pool.ts
> +    for (const worker of this.workers) {
Is this needed? I see lots of other usage of for...of in this repo.

2023-01-22 17:31 UTC, dasa commented on packages/terser/src/worker-pool.ts
> +type WorkerWithTaskInfo = Worker & { [taskInfo]?: null | WorkerPoolTaskInfo };
> types should be located in `type.ts` for clearer separation.

This type needs access to the `taskInfo` Symbol though.

2023-01-23 16:57 UTC, tada5hi commented on packages/terser/src/worker-pool.ts
> +    for (const worker of this.workers) {
needed not, but i like nativ for loops more ^^

2023-01-23 17:26 UTC, tada5hi commented on packages/terser/src/worker-pool.ts
> +type WorkerWithTaskInfo = Worker & { [taskInfo]?: null | WorkerPoolTaskInfo };
would be great if you could create a `constants.ts` file and export `taskInfo` and `freeWorker` from there and than use those epxorts for the `WorkerWithTaskInfo` type in the `type.ts` file :v:

2023-01-23 17:29 UTC, tada5hi commented on packages/terser/src/worker-pool.ts
> +type WorkerWithTaskInfo = Worker & { [taskInfo]?: null | WorkerPoolTaskInfo };
@dasa after that the pull request should fit from my side like this

2023-01-23 17:54 UTC, dasa commented on packages/terser/src/worker-pool.ts
> +type WorkerWithTaskInfo = Worker & { [taskInfo]?: null | WorkerPoolTaskInfo };
👍🏻

2023-01-23 17:59 UTC, dasa commented
@tada5hi I believe I've addressed all your feedback. Please let me know if there's anything else.

2023-01-23 21:03 UTC, tada5hi approved these changes

2023-01-23 21:11 UTC, merged

2023-01-23 21:15 UTC, shellscape commented
@tada5hi please try to wait for two approvals, thats the standard we tend to follow. if after a week or so no one has stepped up to review, we'll ping people direct and if at that point it's crickets, we'll merge. we're definitely not in a rush to merge in this project.

2023-01-23 21:21 UTC, tada5hi commented
> @tada5hi please try to wait for two approvals, thats the standard we tend to follow. if after a week or so no one has stepped up to review, we'll ping people direct and if at that point it's crickets, we'll merge. we're definitely not in a rush to merge in this project. 

@shellscape Oh dam I'm sorry about that. I assumed from past experience that one approval would be enough. I will definitely keep it in mind in the future and follow the convention. Would like to apologize again for the circumstances.

2023-01-23 21:22 UTC, shellscape commented
No worries, no need to apologize. We should probably write that down somewhere.