fix(yaml): Add extensions?: string[] to RollupYamlOptions
rollup/plugins pull request #1506
Opened 2023-05-24 18:46 UTC by janosh

Follow up to #1445.

## Rollup Plugin Name: `yaml`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

Follow up to #1445.

Fixes:

![Screenshot 2023-05-24 at 11 45 25](https://github.com/rollup/plugins/assets/30958850/392f1d32-6038-4d58-80cd-3c9d2eb97873)

2023-05-26 11:38 UTC, shellscape commented
Our PR and Issue templates are not optional. please replace abs update the PR template.

2023-05-26 13:32 UTC, janosh commented
abs?

2023-06-07 01:47 UTC, shellscape requested changes
Thanks for the PR. We require new or updated tests for every PR opened. In this case, we need to assert that the type is correct by updating the `test/types.ts` file. Please add the `extensions` option to that code and we should be good.

2023-06-07 02:56 UTC, janosh commented
@shellscape Thanks for pointer. Added.

2023-06-19 13:43 UTC, shellscape approved these changes

2023-06-19 13:54 UTC, merged