Allow a "no files found" error to be emitted as warning
rollup/plugins pull request #1625
Opened 2023-11-06 09:52 UTC by koddsson

## Rollup Plugin Name: `dynamic-import-vars`

This PR contains:

- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: https://github.com/rollup/plugins/pull/1611

### Description

This PR allows the "no files found" error introduced in https://github.com/rollup/plugins/pull/1611 to be emitted as a warning using the existing `warnOnError` option.

2023-11-13 07:55 UTC, koddsson commented
Hey @shellscape! Could you take a look at this when you have time? Thanks :)

2023-11-25 14:59 UTC, shellscape requested changes

2023-11-25 14:59 UTC, shellscape commented on packages/dynamic-import-vars/README.md
> +When used in combination for `warnOnError` it will throw a warning instead.
```suggestion
⚠️ _Important:_ Enabling this option when `warnOnError` is set to `true` will result in a warning and _not_ an error
```

We need to emphasize the importance of how those work together.

2023-11-25 15:00 UTC, shellscape commented
Sorry about the latency on reviewing. A little bananas on my end lately.

2023-11-28 13:31 UTC, koddsson commented
> Sorry about the latency on reviewing. A little bananas on my end lately.

All good! I never know the etiquette as some people are busy and others just forgot or missed the notification 😄

2023-11-28 14:39 UTC, merged