Added .jpeg and .webp to be included by default
rollup/plugins pull request #625
Opened 2020-10-28 17:33 UTC by bjon

## Rollup Plugin Name: `url`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

### Description

This change will include jpeg and webp files, to the `defaultInclude` list.

Also see: https://github.com/sveltejs/sapper-template/pull/285

2020-10-28 17:41 UTC, NotWoods requested changes
Looks good! Can you please add a test for the new extensions? Once that's done this should be good to merge.

2020-10-28 17:41 UTC, NotWoods commented on packages/url/README.md
> +Default: `['**/*.svg', '**/*.png', '**/*.jp(e)?g', '**/*.gif', '**/*.webp']`
Does `jpe?g` work?

2020-10-28 17:42 UTC, bjon commented on packages/url/README.md
> +Default: `['**/*.svg', '**/*.png', '**/*.jp(e)?g', '**/*.gif', '**/*.webp']`
without () ?

2020-10-28 17:45 UTC, bjon commented on packages/url/README.md
> +Default: `['**/*.svg', '**/*.png', '**/*.jp(e)?g', '**/*.gif', '**/*.webp']`
> Looks good! Can you please add a test for the new extensions? Once that's done this should be good to merge.

I'll try my best

2020-10-28 18:29 UTC, NotWoods approved these changes

2020-11-07 13:52 UTC, merged

2020-11-07 13:52 UTC, shellscape commented
_Note for the future: We'll probably want to start using a thorough list of supported asset types, as @lukastaegert mentioned in another PR, should we get additional requests to expand this list._

![thanks!](https://i.imgur.com/BrUW1rG.jpg)