Check types ci
rollup/plugins pull request #780
Opened 2021-01-29 16:42 UTC by fernandopasik

## Rollup Plugin Name: `{name}`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no (adds tasks to projects and ci)

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:
fixes #779 

### Description

Have early feedback in every PR that typescript types are not compromised.
Add task test:ts to every plugin written in typescript
Run  test:ts on circle ci config

2021-01-29 22:39 UTC, NotWoods requested changes
I think "check" or "typecheck" would be a better script name

2021-01-29 22:39 UTC, NotWoods commented on .circleci/config.yml
> +          name: Run check TS types.
```suggestion
          name: Check TypeScript types.
```

2021-01-29 23:08 UTC, fernandopasik commented
Hi @NotWoods, after a bit more thought I asked some question about this approach here https://github.com/rollup/plugins/issues/779#issuecomment-769987045

> I think I'm missing context on why is it necessary to commit the types/index.d.ts when the source is already typescript. I was expecting that file to be generated along side the js files before publishing to npm only. @shellscape Do you have more information on this?

I don't think the `test:ts` task is checking well the types. I checked this reverting locally the changes in https://github.com/rollup/plugins/pull/647 and it doesn't catch the error.
It did catch it if I directly run `tsc --noEmit`, because that runs on all ts files of the plugin.

2021-01-31 14:22 UTC, shellscape commented
So I know that historically we've had the the `index.d.ts` files hand-written before plugins were moved to TypeScript. That made an additional test of the types necessary. Some of those have stuck around. We even have some TypeScript-sourced plugins (maybe they're all like this still?) that have a separate, hand-written `index.d.ts`, which again is important to check against the code.

In the case of plugins which are already switched over to TypeScript sources, we should probably be generating the definitions at build time, and then removing the additional type check tests (as you point out, it'd be unnecessary). If we do that, for any plugin which uses generated definitions rather than the hand-written definition, we'll have to do a separate PR for each plugin.

2021-02-06 02:14 UTC, fernandopasik commented
Ok, sounds good @shellscape. But for the scope of this PR I managed to deliver the type checking by checking all the ts files in each package, not just the `index.d.ts` like before.

@NotWoods I've merged your proposed change.

2021-02-13 21:38 UTC, NotWoods approved these changes

2021-02-14 14:11 UTC, merged