fix(node-resolve): fix "browser" field mappings.
rollup/plugins pull request #786
Opened 2021-02-01 07:07 UTC by DorianBlues

## Rollup Plugin Name: `node-resolve`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: #472, #540

### Description

When `browser` option of node-resolve is `true`, the package.json browser filed should override the export map result. 
But I found that node-resolve not handled it correctly when use commonjs to require some pacakage. (e.g. nanoid)

2021-02-01 07:51 UTC, guybedford requested changes
I think we should modify this so that the "browser" exports should take precedence over the base-level "browser" field, as otherwise it will be too confusing when each will apply.

2021-02-02 02:08 UTC, DorianBlues commented
I found that the "browser" exports of package `nanoid` has optimization conditions: `development` and `production` which now are supported by webpack. Should we change the type of "browser" option of node-resolve to string so that we can support it.

2021-02-02 08:30 UTC, guybedford commented
@DorianBlues right, you can enable these via `"conditions": ["development"]` etc also being passed to the plugin.

It might also make sense for RollupJS to default to a development or production condition, for cases where these are treated as mutually exclusive by packages like nanoid. Note these are now all endorsed by Node.js fwiw (https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_conditions_definitions). //cc @LarsDenBakker

2021-03-10 15:21 UTC, shellscape commented
@DorianBlues please give this PR some attention. When PRs have no activity for 30 days, we typically close them as abandoned unless the author responds.

2021-04-22 13:12 UTC, closed without merging